# Generated by Django 5.1 on 2024-10-24 11:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaMunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DescautelasCa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_cautela', models.DateTimeField()),
                ('policial', models.CharField(max_length=100)),
                ('tipo_servico', models.CharField(max_length=50)),
                ('categoria_armamento', models.CharField(max_length=50, null=True)),
                ('subcategoria_armamento', models.CharField(max_length=50, null=True)),
                ('categoria_municao', models.CharField(max_length=50, null=True)),
                ('subcategoria_municao', models.CharField(max_length=50, null=True)),
                ('quantidade_municao', models.IntegerField()),
                ('situacao_armamento', models.CharField(max_length=50)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('armeiro', models.CharField(max_length=100)),
                ('armeiro_descautela', models.CharField(max_length=100)),
                ('data_descautelamento', models.DateField()),
                ('hora_descautelamento', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PassagemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_cautela_id', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('nome_substituto', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('nome_guerra', models.CharField(blank=True, max_length=50, null=True)),
                ('posto_graduacao', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('rgpm', models.CharField(max_length=20, unique=True)),
                ('lotacao', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCautelaCompleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_servico', models.CharField(max_length=20)),
                ('categoria_armamento', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategoria_armamento', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria_municao', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategoria_municao', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade_municao', models.PositiveIntegerField(default=0)),
                ('armeiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cautelaarmamento.policial')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDescautelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_cautela', models.DateTimeField()),
                ('tipo_servico', models.CharField(max_length=100)),
                ('categoria_armamento', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategoria_armamento', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria_municao', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategoria_municao', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade_municao', models.PositiveIntegerField(default=0)),
                ('situacao_armamento', models.CharField(blank=True, max_length=20, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_descautelamento', models.DateField(auto_now_add=True)),
                ('hora_descautelamento', models.TimeField(auto_now_add=True)),
                ('armeiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrodescautelamento_armeiro', to=settings.AUTH_USER_MODEL)),
                ('armeiro_descautela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrodescautelamento_armeiro_descautela', to=settings.AUTH_USER_MODEL)),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cautelaarmamento.policial')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('chassi', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('procedencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True)),
                ('aparencia_visual', models.TextField(blank=True, null=True, verbose_name='Aparência Visual')),
                ('estado_conservacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='EST. DE CONSERVAÇÃO')),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=50, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=200, null=True)),
                ('destinacao', models.CharField(blank=True, max_length=100, null=True)),
                ('situacao', models.CharField(choices=[('disponivel', 'Disponível'), ('cautelada', 'Cautelada'), ('extraviado', 'Extraviado'), ('roubado', 'Roubado'), ('quebrado', 'Quebrado'), ('furado', 'Furado'), ('disparado', 'Disparado')], default='disponivel', max_length=20)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('cal', models.CharField(blank=True, max_length=50, null=True)),
                ('ct', models.CharField(blank=True, max_length=50, null=True)),
                ('num_arma', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nº ARMA')),
                ('num_pmma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº PMMA')),
                ('tombo', models.CharField(blank=True, max_length=100, null=True)),
                ('gr', models.CharField(blank=True, max_length=50, null=True, verbose_name='GR')),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='OBSERVAÇÃO')),
                ('descricao_completa', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias_armamento', to='cautelaarmamento.categoria')),
                ('inserido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CautelaDeArmamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('operacional', 'Operacional'), ('administrativo', 'Administrativo')], max_length=20)),
                ('hora_cautela', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmado', models.BooleanField(default=False)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('armeiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cautelaarmamento.categoria')),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cautelaarmamento.policial')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cautelaarmamento.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoriaMunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('total_de_municoes', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='cautelaarmamento.categoriamunicao')),
            ],
        ),
        migrations.CreateModel(
            name='CautelaDeMunicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cautelaarmamento.categoriamunicao')),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cautelaarmamento.policial')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cautelaarmamento.subcategoriamunicao')),
            ],
        ),
    ]
