# Generated by Django 5.1 on 2024-08-25 22:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armas',
            fields=[
                ('numero_ordem', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('calibre', models.CharField(max_length=10)),
                ('ct', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_arma', models.CharField(max_length=50)),
                ('numero_pmma', models.CharField(blank=True, max_length=50, null=True)),
                ('localizacao', models.CharField(max_length=100)),
                ('estado_conservacao', models.CharField(max_length=50)),
                ('grupo_responsavel', models.CharField(blank=True, max_length=50, null=True)),
                ('processo', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cautelado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('CALOI', 'Caloi'), ('MONARK', 'Monark'), ('HOUSTON', 'Houston'), ('SCOTT', 'Scott'), ('TREK', 'Trek'), ('GTS', 'GTS'), ('SHIMANO', 'Shimano'), ('GHOST', 'Ghost')], max_length=50)),
                ('tipo', models.CharField(choices=[('MTB', 'Mountain Bike'), ('URBANA', 'Urbana'), ('SPEED', 'Speed'), ('BMX', 'BMX'), ('ELETRICA', 'Elétrica'), ('FIXA', 'Fixa'), ('HIBRIDA', 'Híbrida')], max_length=50)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('procedencia', models.CharField(max_length=100)),
                ('doc_ref', models.CharField(max_length=100, verbose_name='Documento de Referência')),
                ('situacao', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em uso'), ('MANUTENCAO', 'Manutenção'), ('BAIXADO', 'Baixado'), ('RESERVA', 'Reserva')], max_length=50)),
                ('tombo', models.CharField(max_length=50, unique=True)),
                ('localizacao', models.CharField(max_length=100)),
                ('cautelado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('numero_ordem', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(choices=[('HONDA', 'Honda'), ('YAMAHA', 'Yamaha'), ('SUZUKI', 'Suzuki'), ('KAWASAKI', 'Kawasaki'), ('BMW', 'BMW'), ('HARLEY-DAVIDSON', 'Harley-Davidson')], max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10)),
                ('chassi', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('processo', models.CharField(max_length=100)),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True)),
                ('aparencia_visual', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('situacao', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em uso'), ('MANUTENCAO', 'Manutenção'), ('BAIXADO', 'Baixado'), ('RESERVA', 'Reserva')], max_length=50)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cautelado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Municoes',
            fields=[
                ('numero_ordem', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('calibre', models.CharField(blank=True, max_length=50, null=True)),
                ('data_recebimento', models.DateField()),
                ('grupo_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('processo', models.CharField(blank=True, max_length=100, null=True)),
                ('recebida', models.IntegerField()),
                ('consumida', models.IntegerField(default=0)),
                ('saldo', models.IntegerField(default=0)),
                ('cautelada', models.IntegerField(blank=True, default=0, null=True)),
                ('descarregadas', models.IntegerField(blank=True, default=0, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('situacao', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('cautelado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PolicialMilitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('numero_identificacao', models.CharField(max_length=50, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('patente', models.CharField(max_length=50)),
                ('unidade', models.CharField(max_length=100)),
                ('data_ingresso', models.DateField()),
                ('lotacao_atual', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('reserva', 'Reserva'), ('reformado', 'Reformado')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Policial Militar',
                'verbose_name_plural': 'Policiais Militares',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Vtr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('TOYOTA', 'Toyota'), ('FORD', 'Ford'), ('CHEVROLET', 'Chevrolet'), ('FIAT', 'Fiat'), ('VOLKSWAGEN', 'Volkswagen'), ('MITSUBISHI', 'Mitsubishi'), ('RENAULT', 'Renault'), ('JEEP', 'Jeep'), ('HYUNDAI', 'Hyundai'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('TROLLER', 'Troller')], max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10)),
                ('chassi', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('procedencia', models.CharField(max_length=100)),
                ('fornecedor', models.CharField(max_length=100)),
                ('aparencia_visual', models.TextField()),
                ('destino', models.CharField(max_length=100)),
                ('situacao', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em uso'), ('MANUTENCAO', 'Manutenção'), ('BAIXADO', 'Baixado'), ('RESERVA', 'Reserva'), ('EM_ABASTECIMENTO', 'Em abastecimento'), ('EM_DESLOCAMENTO', 'Em deslocamento'), ('EM_OPERACAO', 'Em operação'), ('RETORNO', 'Retornando'), ('EM_REVISAO', 'Em revisão'), ('EM_ADAPTACAO', 'Em adaptação'), ('DESATIVADO', 'Desativado'), ('EM_TREINAMENTO', 'Em treinamento'), ('EM_REMOCAO', 'Em remoção'), ('SOB_AVALIACAO', 'Sob avaliação'), ('EM_VISTORIA', 'Em vistoria')], max_length=50)),
                ('localizacao', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('locada', models.BooleanField(default=False)),
                ('cautelado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cautela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cautelado', models.BooleanField(default=False)),
                ('data_cautela', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_descautela', models.DateTimeField(blank=True, null=True)),
                ('arma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cautelaarmamento.armas')),
                ('bicicleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cautelaarmamento.bicicleta')),
                ('moto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cautelaarmamento.moto')),
                ('municao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cautelaarmamento.municoes')),
                ('policial_militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cautelaarmamento.policialmilitar')),
                ('vtr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cautelaarmamento.vtr')),
            ],
        ),
    ]
