# Generated by Django 5.1 on 2024-09-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='nome_guerra',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='tipo_servico',
        ),
    ]
