# Generated by Django 5.1 on 2024-10-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='cal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='ct',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='estado_conservacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EST. DE CONSERVAÇÃO'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='gr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='G.R'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='num_arma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº ARMA'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='num_pmma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº PMMA'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='OBSERVAÇÃO'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='proc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PROC'),
        ),
    ]
