# Generated by Django 5.1 on 2024-08-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtr',
            name='marca',
            field=models.CharField(choices=[('TOYOTA', 'Toyota'), ('FORD', 'Ford'), ('CHEVROLET', 'Chevrolet'), ('FIAT', 'Fiat'), ('VOLKSWAGEN', 'Volkswagen'), ('MITSUBISHI', 'Mitsubishi'), ('RENAULT', 'Renault'), ('JEEP', 'Jeep'), ('HYUNDAI', 'Hyundai'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('TROLLER', 'Troller')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vtr',
            name='situacao',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em uso'), ('MANUTENCAO', 'Manutenção'), ('BAIXADO', 'Baixado'), ('RESERVA', 'Reserva'), ('EM_ABASTECIMENTO', 'Em abastecimento'), ('EM_DESLOCAMENTO', 'Em deslocamento'), ('EM_OPERAÇÃO', 'Em operação'), ('RETORNO', 'Retornando'), ('EM_REVISAO', 'Em revisão'), ('EM_ADAPTACAO', 'Em adaptação'), ('DESATIVADO', 'Desativado'), ('EM_TREINAMENTO', 'Em treinamento'), ('EM_REMOCAO', 'Em remoção'), ('SOB_AVALIACAO', 'Sob avaliação'), ('EM_VISTORIA', 'Em vistoria')], max_length=50),
        ),
    ]
