# Generated by Django 5.1 on 2024-11-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='chassi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='num_arma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº ARMA'),
        ),
    ]
