# Generated by Django 5.1 on 2024-10-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauteladearmamento',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cauteladearmamento',
            name='confirmado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
