# Generated by Django 5.1 on 2024-09-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria_municoes',
            name='situacao',
        ),
    ]
