# Generated by Django 5.1 on 2024-08-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armas',
            name='disponivel',
            field=models.CharField(choices=[('Disponivel', 'Disponível'), ('Indisponivel', 'Indisponível'), ('verificar', 'Verificar'), ('manutencao', 'Manutenção'), ('quebrada', 'Quebrada')], max_length=20),
        ),
    ]
