# Generated by Django 5.1 on 2024-10-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descautelasca',
            name='categoria_armamento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='descautelasca',
            name='categoria_municao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='descautelasca',
            name='subcategoria_municao',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
