# Generated by Django 5.1 on 2024-09-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policial',
            name='restricao',
        ),
        migrations.AddField(
            model_name='cauteladearmamento',
            name='tipo_servico',
            field=models.CharField(choices=[('24HORAS', '24 Horas'), ('QTU', 'QTU (12 Horas)'), ('GIRO', 'Giro (6 Horas)'), ('EXPEDIENTE', 'Expediente (8 Horas)'), ('PLANTAO', 'Plantão')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
