# Generated by Django 5.1 on 2024-08-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtr',
            name='chassi',
            field=models.CharField(max_length=50),
        ),
    ]
