# Generated by Django 5.1 on 2024-12-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descautelasca',
            name='categoria_armamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='descautelasca',
            name='categoria_municao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='descautelasca',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descautelasca',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descautelasca',
            name='situacao_armamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='descautelasca',
            name='subcategoria_armamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='descautelasca',
            name='subcategoria_municao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
