# Generated by Django 5.1 on 2024-12-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0002_alter_descautelasca_categoria_armamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policial',
            name='autorizacao_arma',
            field=models.BooleanField(default=False),
        ),
    ]
