# Generated by Django 5.1 on 2024-09-19 11:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0002_cauteladearmamento_armeiro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCautelaCompleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_servico', models.CharField(max_length=20)),
                ('categoria_armamento', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategoria_armamento', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria_municao', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategoria_municao', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade_municao', models.PositiveIntegerField(default=0)),
                ('armeiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cautelaarmamento.policial')),
            ],
        ),
    ]
