# Generated by Django 5.1 on 2024-09-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0002_remove_policial_restricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauteladearmamento',
            name='tipo_servico',
            field=models.CharField(choices=[('24HORAS', '24 Horas'), ('QTU', 'QTU (12 Horas)'), ('GIRO', 'Giro (6 Horas)'), ('EXPEDIENTE', 'Expediente (8 Horas)'), ('PERMANENTE', 'Permanente')], max_length=10),
        ),
    ]
