# Generated by Django 5.1 on 2024-09-15 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0002_remove_subcategoria_nome_guerra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armamentocautelado',
            name='nome_guerra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias_armamento', to='cautelaarmamento.policial'),
        ),
        migrations.AddField(
            model_name='armamentocautelado',
            name='tipo_servico',
            field=models.CharField(blank=True, choices=[('24HORAS', '24 Horas'), ('QTU', 'QTU (12 Horas)'), ('GIRO', 'Giro (6 Horas)'), ('EXPEDIENTE', 'Expediente (8 Horas)'), ('PERMANENTE', 'Permanente')], max_length=10, null=True),
        ),
    ]
