# Generated by Django 5.1 on 2024-08-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0002_alter_vtr_marca_alter_vtr_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtr',
            name='placa',
            field=models.CharField(max_length=10),
        ),
    ]
