# Generated by Django 5.1 on 2024-10-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0002_alter_descautelasca_categoria_armamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descautelasca',
            name='subcategoria_armamento',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
