# Generated by Django 5.1 on 2024-11-02 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0002_cautelademunicoes_armeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cautelademunicoes',
            name='hora_cautela',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
