# Generated by Django 5.1 on 2024-10-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0002_cauteladearmamento_confirmado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
