# Generated by Django 5.1 on 2024-10-17 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0003_alter_subcategoria_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassagemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhes_armamento_municao', models.JSONField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
