# Generated by Django 5.1 on 2024-10-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0003_alter_descautelasca_subcategoria_armamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='descautelasca',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
