# Generated by Django 5.1 on 2024-08-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0003_armas_moto_policialmilitar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municoes',
            fields=[
                ('numero_ordem', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('calibre', models.CharField(blank=True, max_length=50, null=True)),
                ('data_recebimento', models.DateField()),
                ('grupo_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('processo', models.CharField(blank=True, max_length=100, null=True)),
                ('recebida', models.IntegerField()),
                ('consumida', models.IntegerField()),
                ('saldo', models.IntegerField()),
                ('cautelada', models.IntegerField(blank=True, null=True)),
                ('descarregadas', models.IntegerField(blank=True, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('situacao', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
