# Generated by Django 5.1 on 2024-11-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0003_cautelademunicoes_hora_cautela'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cautelademunicoes',
            old_name='hora_cautela',
            new_name='data_descautelamento',
        ),
    ]
