# Generated by Django 5.1 on 2024-08-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0003_alter_vtr_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtr',
            name='locada',
            field=models.BooleanField(default=False),
        ),
    ]
