# Generated by Django 5.1 on 2024-08-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0004_vtr_locada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('CALOI', 'Caloi'), ('MONARK', 'Monark'), ('HOUSTON', 'Houston'), ('SCOTT', 'Scott'), ('TREK', 'Trek'), ('GTS', 'GTS'), ('SHIMANO', 'Shimano'), ('GHOST', 'Ghost')], max_length=50)),
                ('tipo', models.CharField(choices=[('MTB', 'Mountain Bike'), ('URBANA', 'Urbana'), ('SPEED', 'Speed'), ('BMX', 'BMX'), ('ELETRICA', 'Elétrica'), ('FIXA', 'Fixa'), ('HÍBRIDA', 'Híbrida')], max_length=50)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('procedencia', models.CharField(max_length=100)),
                ('doc_ref', models.CharField(max_length=100, verbose_name='Documento de Referência')),
                ('situacao', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em uso'), ('MANUTENCAO', 'Manutenção'), ('BAIXADO', 'Baixado'), ('RESERVA', 'Reserva')], max_length=50)),
                ('tombo', models.CharField(max_length=50, unique=True)),
                ('localizacao', models.CharField(max_length=100)),
            ],
        ),
    ]
