# Generated by Django 5.1 on 2024-11-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0004_rename_hora_cautela_cautelademunicoes_data_descautelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagemdeservico',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
