# Generated by Django 5.1 on 2024-09-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0004_registrodescautelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='situacao',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('cautelada', 'Cautelada'), ('extraviado', 'Extraviado'), ('roubado', 'Roubado'), ('quebrado', 'Quebrado'), ('furado', 'Furado'), ('disparado', 'Disparado')], default='disponivel', max_length=20),
        ),
    ]
