# Generated by Django 5.1 on 2024-10-21 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0004_passagemdeservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='passagemdeservico',
            name='registro_cautela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cautelaarmamento.registrocautelacompleta'),
            preserve_default=False,
        ),
    ]
