# Generated by Django 5.1 on 2024-09-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0005_alter_subcategoria_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodescautelamento',
            name='situacao_armamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
