# Generated by Django 5.1 on 2024-09-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautelaarmamento', '0006_registrodescautelamento_situacao_armamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodescautelamento',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
